version: '3.2'
services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/logs:/var/lib/mysql-logs
        - ./mysql/conf:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
        - ./redis/data:/data
        # - ./redis/logs:/logs
        # - ./redis/conf:/usr/local/etc/redis:ro
    restart: always

  caddy:
    build: ./caddy
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"
    volumes:
      - ${PROJ_PATH}:/proj
      - ./caddy/conf/${CADDYFILE_NAME}:/etc/Caddyfile
      - ./caddy/data:/root/.caddy
      - ./caddy/logs:/logs

  php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - caddy
    volumes:
      - ${PROJ_PATH}:/proj
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/logs:/var/log/php-fpm
    restart: always
    command: php-fpm
      
  gogs:
    links:
      - mysql
    build: ./gogs
    ports:
      - "10022:22"
      - "3000:3000"
    volumes:
      - ./gogs/conf:/data/gogs/conf
      - ./gogs/data/git:/data/git/gogs-repositories
      - ./gogs/data/db:/data/gogs/data
      - ./gogs/logs:/app/gogs/log
    environment:
      - "SOCAT_LINK=true"
      - "RUN_CROND=true"

  workspace:
    build: ./workspace
    ports:
      - "7009:7009" # webhook
      - "893:893" # kodExplorer
      - "8443:8443" # vscoder
      # 开放常用端口便于开发调试
      - "50003:3"
      - "50020:20"
      - "50021:21"
      - "50022:22"
      - "50080:80"
      - "50081:81"
      - "50443:443"
      - "58000:8000"
      - "58080:8080"
      - "58081:8081"
    volumes:
      - ${PROJ_PATH}:/proj
      - /root/.ssh:/root/.ssh
      - ./workspace/kodexplorer:/app/kodexplorer
      - ./workspace/webhook/hooks.json:/app/webhook/hooks.json
      - ./workspace/webhook/shellscript:/shellscript
      - ./workspace/code-server/expansions:/app/code-server/expansions
      - ./workspace/code-server/home:/app/code-server/home
      - ./workspace/code-server/password:/app/code-server/password
    command: [ "/bin/bash", "/app/run.sh" ]
    tty: true
